config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'game_sessions/update_games', as: 'update_games'
  get 'home/game', to: 'home#sort_by_game', as: 'sort_by_game'
  get 'home/game_mode', to: 'home#sort_by_game_mode', as: 'sort_by_game_mode'
  post 'game_sessions/:id/join_game', to: 'game_sessions#join_game', as: 'join_game'
  post 'game_sessions/:id/leave_game', to: 'game_sessions#leave_game', as: 'leave_game'
  resources :game_sessions

  get 'home/index'

  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :games

  resources :users

  root 'home#index'

end

app/controllers/home_controller.rb
# Home Root Controller
class HomeController < ApplicationController
	load_resource :game_session
  def index
		authorize! :edit, GameSession
    @game_sessions = GameSession.includes(:users, :game, :game_mode)
  end

  def sort_by_game
    @game_sessions = GameSession.where('game_id = ?', params[:game_id])
    respond_to do |format|
      format.js
    end
  end

  def sort_by_game_mode
    @game_sessions = GameSession.where('game_mode_id = ?', params[:game_mode_id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_filter_game_sessions.html.erb
<div class="ui floating labeled icon dropdown button">
  <i class="filter icon"></i>
  <span class="text">Filter</span>
  <div class="menu">
    <div class="header">
      Search Games
    </div>
    <div class="ui left icon input">
      <i class="search icon"></i>
      <input type="text" name="search" placeholder="Search...">
    </div>
    <div class="header">
      <i class="tags icon"></i>
      Filter by Game
    </div>
    <% cache do %>
      <% Game.all.each do |game| %>
        <div class="item filter-session" data-id="<%= game.id %>">
          <%= game.title %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/home/_game_session_cards.html.erb
<h2 class="ui header">Current Gaming Sessions</h2>
  <div class="ui divider"></div>
  <%= render 'home/filter_game_sessions' %>
  <%= render 'home/new_game_button' %>

  <div class="ui divider"></div>

  <div class="ui cards game-cards">
    <% @game_sessions.each do |game_session| %>
    <div class="ui card">
      <p class="image">
        <%= image_tag game_session.game.game_icon.url %>
      </p>
      <div class="content">
        <%= link_to game_session.game.title.titleize + " | " +  game_session.game_mode.title.titleize, game_session, class: "header" %>
        <div class="meta">
          <p>users: <%= game_session.users.count %>/<%= game_session.game_mode.total_players %></p>
          <div class="ui divided list">
            <% game_session.users.each do |user| %>
            <div class="item">
              <%= image_tag user.avatar.url, class: "ui avatar image" %>
              <div class="content">
                <div class="header"><%= link_to user.user_name, user_path(user) %></div>
              </div>
            </div>
            <% end %>
          </div>
        </div>
        
        <div class="ui divider"></div>
        
        <div class="description">
          <p><strong>Notes:</strong> <%= game_session.notes%></p>
          <p><strong>Game Date:</strong> <%= local_date(game_session.game_date, '%B %e') %></p>
          <p><strong>Start Time:</strong> <%= local_time(game_session.start_time, '%l:%M%P') %></p>
          <p><strong>End Time:</strong> <%= local_time(game_session.end_time, '%l:%M%P') %></p>
          
          <div class="ui divider"></div>
          
          <% if user_signed_in? && game_session.users.ids.include?(current_user.id) %>
            <%= button_to 'Leave Game', leave_game_path(game_session), action: "leave_game", class: "game-button mini ui primary button" %>
            <% if can? :edit, GameSession %>
                <%= button_to 'Edit Session', edit_game_session_path(game_session), method: :get, class: "game-button mini ui orange button" %>
            <% end %>
          <% else %>
            <%= link_to 'Join Game', join_game_path(game_session), action: "join_game", method: :post, class: "game-button mini ui primary button" %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>

app/views/home/_new_game_button.html.erb
<%= link_to raw('Create Gaming Session <i class="add circle icon"></i>'), new_game_session_path, {class: "ng-session ng-button tiny ui primary button"}%>

app/views/home/index.html.erb
<div class="sixteen wide column">
  <%= render 'game_session_cards' %>
</div>
<div class="fourteen wide centered row">
  <h2>Most Played Games</h2>
  <div class="ui divider"></div>
</div>