config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'game_sessions/update_games', as: 'update_games'
  get 'home/game', to: 'home#sort_by_game', as: 'sort_by_game'
  get 'home/game_mode', to: 'home#sort_by_game_mode', as: 'sort_by_game_mode'
  post 'game_sessions/:id/join_game', to: 'game_sessions#join_game', as: 'join_game'
  post 'game_sessions/:id/leave_game', to: 'game_sessions#leave_game', as: 'leave_game'
  resources :game_sessions

  get 'home/index'

  devise_for :users, :controllers => { :registrations => "user/registrations" }
  resources :games

  resources :users

  root 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :game_modes, dependent: :destroy
  validates_associated :game_modes

  has_many :game_sessions, through: :game_modes
  accepts_nested_attributes_for :game_modes, :game_sessions

  validates :title, :description, presence: true

  has_attached_file :game_icon, styles: { game_card: '650x350', medium: '325x175>', thumb: '130x70>' }, default_url: '/images/:style/missing_game_icon.png'
  validates_attachment_content_type :game_icon, content_type: ['image/jpg', 'image/jpeg', 'image/gif', 'image/png']
end

app/controllers/games_controller.rb
# Games Controller
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
	load_and_authorize_resource

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:title, :description, :game_icon)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<div class="ten wide centered column">
  <div class="ui attached message">
      <div class="header">
        Game Form
      </div>
  </div>
    <%= form_for @game, html: {class: "ui form attached fluid segment"} do |f| %>
      <% if @game.errors.any? %>
        <div id="error_explanation" class="ui negative message">
          <i class="close icon"></i>
          <div class="header"<%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</div>

          <ul>
            <% @game.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="required field">
        <%= f.label :title %><br>
        <%= f.text_field :title, required: true %>
      </div>

      <div class="field">
        <%= f.label :game_icon, "Game Icon" %>
        <% if @game.game_icon.exists? %>
          <%= image_tag @game.game_icon.url(:medium) %><br />
        <% end %>
        <%= f.file_field :game_icon %>
      </div>

      <div class="required field">
        <%= f.label :description %><br>
        <%= f.text_area :description, required: true %>
      </div>

      <div class="actions">
        <%= f.submit "Submit", class: "ui right floated green button" %>
      </div>
    <% end %>
</div>

app/views/games/edit.html.erb
<div class="ui ten wide column centered orange segment">
  <h1 class="ui header">
    <i class="write square icon"></i> 
    <div class="content">Editing Game</div>
  </h1>
</div>

<%= render 'form' %>

app/views/games/index.html.erb
<div class="ui floating message">
  
  <p id="notice"><%= notice %></p>
  
</div>

<div class="twelve wide centered column">
  
  
  <div class="ui segment">
    
    
    <div class="ui divided items">
      
      <div class="item">
        
        <%= link_to 'New Game', new_game_path, class:"ui right floated green button" %>
        
      </div>
      
      <% @games.each do |game| %>
      
      <div class="item">
        
        <div class="image">
          
          <%= image_tag game.game_icon.url %>
          
        </div>
        
        <div class="content">
          
          <h3><%= link_to game.title, game_url(game) %></h3>
          
          <div class="description">
            
            <p><%= game.description %></p>
            
          </div>
          
          <div class="extra">
            
            <h4>Game Modes:</h4>
            
            <% game.game_modes.each do |game_mode| %>
            
              <div class="ui large teal label"><%= game_mode.title %></div>
            
            <% end %>
            
            <%= link_to 'Edit', edit_game_path(game),class: "ui right floated orange button" %>
            
            <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, class: "ui right floated red button" %>
            
          </div>
          
        </div>
        
      </div>
      
      <% end %>
      
    </div>
    
  </div>
  
</div>

app/views/games/new.html.erb
<div class="ui ten wide column centered green segment">
  <h1 class="ui header">
    <i class="plus icon"></i>
    <div class="content">New Game</div>
  </h1>
</div>

<%= render 'form' %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<div class="twelve wide centered column">
  
  <div class="ui segment four wide column">
      <div class="ui items">
      <div class="item">
        <p class="image">
          <%= image_tag @game.game_icon.url %>
        </p>
        <div class="content">
          <p class="header"><%= @game.title %></p>
          <div class="description">
            <%= @game.description %>
          </div>
        </div>
        <div class="extra">
          <%= button_to 'Edit', edit_game_path(@game), method: "get", class: "ui right floated orange button" %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="seven wide column">
    <h2>Game Modes</h2>
    <div class="ui divider"></div>
    <table class="ui tablet stackable table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Total Players</th>
          <th class="right aligned">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @game.game_modes.each do |game_mode| %>
          <td><%= game_mode.title %></td>
          <td><%= game_mode.total_players %></td>
          <td><%= link_to 'Destroy', {}, class: "ui right floated red button" %></td>
        <% end %>
      </tbody>
    </table>
  </div>
</div>